project_id = "eemsbitvwxhyrfxoqzhl"
[functions.get-media-signed-urls]
enabled = true
verify_jwt = true
import_map = "./functions/get-media-signed-urls/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-media-signed-urls/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-media-signed-urls/*.html" ]

[functions.send-announcement-push]
enabled = true
verify_jwt = true
import_map = "./functions/send-announcement-push/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-announcement-push/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-announcement-push/*.html" ]
