
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jazoifeaaiwouzvxaoad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphem9pZmVhYWl3b3V6dnhhb2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODgyMDYsImV4cCI6MjA2MTQ2NDIwNn0.vnI43pmJT9QZ1AGds2BTg8D__6dblEGfH-fJfaEBt0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
